[tool.poetry]
authors = ["Johannes Köster <johannes.koester@uni-due.de>"]
description = "This package provides a stable interface for interactions between Snakemake and its executor plugins."
license = "MIT"
name = "snakemake-executor-plugin-interface"
packages = [{include = "snakemake_executor_plugin_interface"}]
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
argparse-dataclass = "^2.0.0"
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
coverage = {extras = ["toml"], version = "^6.3.1"}
flake8 = "^4.0.1"
flake8-bugbear = "^22.1.11"
pytest = "^7.0"
snakemake = "*"
snakemake-executor-flux = {git = "https://github.com/snakemake/snakemake-executor-flux.git"}

[tool.coverage.run]
omit = [".*", "*/site-packages/*"]

[tool.coverage.report]
# exclude CLI handling lines. They cannot be captured properly by coverage, but we have a testcase for them.
exclude_lines = [
  "yaml\\.dump\\(result, outfile\\)",
  "process_yaml\\(sys.stdin, outfile=sys\\.stdout\\)",
  "plac.call\\(cli\\)",
]
fail_under = 90

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
