name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: []

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install Dependencies using Poetry
        run: |
          pip install connection-pool # because it is incompatible with poetry
          poetry install

      - name: Run pytest
        run: poetry run coverage run -m pytest tests.py

      - name: Run Coverage
        run: poetry run coverage report -m
