name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: []

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Determine dependencies
        run: poetry lock

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: poetry

      - name: Install dependencies
        run: |
          pip install connection-pool # because it is incompatible with poetry
          poetry install

      - name: Install example plugin
        run: |
          pip install --no-dependencies git+https://github.com/snakemake/snakemake-executor-flux.git

      - name: Run pytest
        run: poetry run coverage run -m pytest tests/tests.py

      - name: Run Coverage
        run: poetry run coverage report -m
