name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: []

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install connection-pool # because it is incompatible with poetry
          pip install .

      - name: Install example plugin
        run: |
          git clone https://github.com/snakemake/snakemake-executor-flux.git /tmp/plugin
          cd /tmp/plugin
          pip install .
          cd -

      - name: Run pytest
        run: pytest -xs tests.py
